config/routes.rb
TweetPull::Application.routes.draw do
  resources :tweets

  resources :people

  

end

app/models/person.rb
class Person < ActiveRecord::Base
	has_many :tweets

	TWELVE_PEOPLE = [2,3,4,5,7,8,9,10,11,14,15,16]

	def self.write_data_by_labels file_name_param=nil, number_examples=nil
		file_name = file_name_param || "output_by_labels.txt"
		File.open(Rails.root.to_s + "/" + file_name, "w") do |file|
			Person.order("label_number").each do |person|
				if number_examples
					person.tweets.limit(number_examples).each do |tweet|
						if (tweet.text =~ /^RT/).nil?
							file.puts "#{person.id.to_i}  #{tweet.text}"
						end
					end
				else
					person.tweets.each do |tweet|
						if (tweet.text =~ /^RT/).nil?
							file.puts "#{person.id.to_i} #{tweet.text}"
						end
					end
				end
			end
		end
	end

	def self.write_data_by_people file_name_param=nil, number_examples=nil
		file_name = file_name_param || "output_by_people.txt"
		File.open(Rails.root.to_s + "/" + file_name, "w") do |file|
			Person.where(id: [3,8, 10, 14]).order("id").each do |person|
				if number_examples
					person.tweets.limit(number_examples).each do |tweet|
						if (tweet.text =~ /^RT/).nil?
							file.puts "#{person.id.to_i}  #{tweet.text}"
						end
					end
				else
					person.tweets.limit(number_examples).each do |tweet|
						if (tweet.text =~ /^RT/).nil?
							file.puts "#{person.id.to_i} #{tweet.text}"
						end
					end
				end
			end
		end
	end

	def self.twelve_people_by_group file_name_param=nil, number_examples=nil
		file_name = file_name_param || "output_by_people.txt"
		File.open(Rails.root.to_s + "/" + file_name, "w") do |file|
			Person.where(id: TWELVE_PEOPLE).order("id").each do |person|
				if number_examples
					person.tweets.limit(number_examples).each do |tweet|
						file.puts "#{person.label_number.to_i}  #{tweet.text}"
					end
				else
					person.tweets.limit(number_examples).each do |tweet|
						file.puts "#{person.label_number.to_i} #{tweet.text}"
					end
				end
			end
		end
	end

	def self.twelve_people_by_user file_name_param=nil, number_examples=nil
		file_name = file_name_param || "output_by_people.txt"
		File.open(Rails.root.to_s + "/" + file_name, "w") do |file|
			Person.where(id: TWELVE_PEOPLE).order("id").each do |person|
				if number_examples
					person.tweets.limit(number_examples).each do |tweet|
						file.puts "#{person.id.to_i}  #{tweet.text}"
					end
				else
					person.tweets.limit(number_examples).each do |tweet|
						file.puts "#{person.id.to_i} #{tweet.text}"
					end
				end
			end
		end
	end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:number, :name, :username, :class, :label_number)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tweet }
      else
        format.html { render action: 'new' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:text, :person_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TweetPull</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :class %><br>
    <%= f.text_field :class %>
  </div>
  <div class="field">
    <%= f.label :label_number %><br>
    <%= f.text_field :label_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Name</th>
      <th>Username</th>
      <th>Class</th>
      <th>Label number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.number %></td>
        <td><%= person.name %></td>
        <td><%= person.username %></td>
        <td><%= person.class %></td>
        <td><%= person.label_number %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @person.number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @person.username %>
</p>

<p>
  <strong>Class:</strong>
  <%= @person.class %>
</p>

<p>
  <strong>Label number:</strong>
  <%= @person.label_number %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :person %><br>
    <%= f.text_field :person %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Person</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.text %></td>
        <td><%= tweet.person %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @tweet.text %>
</p>

<p>
  <strong>Person:</strong>
  <%= @tweet.person %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>